const faqs = [
  {
    title: "What is IMAI?",
    content:
      "IMAI is a generative AI platform that creates high-quality images from text prompts. We're focused on pushing the boundaries of visual creativity through intelligent image generation.",
  },
  {
    title: "How does IMAI work?",
    content:
      "You enter a descriptive text prompt, and our AI model transforms it into a unique, high-resolution image. The better the prompt, the more accurate and artistic the result.",
  },
  {
    title: "Is IMAI free to use?",
    content:
      "No, IMAI is a paid platform. All generations require credits, which can be purchased through a subscription or one-time packs Mentioned Above.",
  },
  {
    title: "How do I purchase credits?",
    content:
      "Credits can be purchased from your account dashboard. We offer flexible packages depending on your needs—no subscription required.",
  },
  {
    title: "What kind of prompts work best?",
    content:
      "IMAI works best with detailed, descriptive prompts. You can include styles (e.g., 'cyberpunk', 'oil painting'), camera types, lighting, and even emotions to guide the output.",
  },
  {
    title: "Can I use images generated by IMAI commercially?",
    content:
      "Yes. Paid users are granted full rights to use their generated images for personal or commercial use, as outlined in our terms of service.",
  },
  {
    title: "Can I download the images I generate?",
    content:
      "Yes, all images you generate are downloadable in high resolution from your account gallery.",
  },
  {
    title: "Do I need design or technical skills to use IMAI?",
    content:
      "Not at all. If you can write a sentence, you can generate with IMAI. It's designed to be simple and accessible for everyone.",
  },
  {
    title: "How fast are image generations?",
    content:
      "Most images generate in under 60 seconds, depending on server load and your selected quality level.",
  },
  {
    title: "Can I use IMAI on mobile devices?",
    content:
      "Yes, IMAI is fully responsive and works well in most modern mobile browsers. A native app is planned for future release.",
  },
  {
    title: "What happens if I run out of credits?",
    content:
      "You can always purchase additional credits. We’ll notify you when your balance is low so you’re never caught off guard.",
  },
  {
    title: "Is there any moderation or safety system in place?",
    content:
      "Yes, we have content filters to prevent harmful or inappropriate generations. We’re committed to responsible and ethical AI use.",
  },
  {
    title: "Can I see examples before purchasing?",
    content:
      "Yes! Our homepage and gallery feature samples generated by real prompts. These show the variety and quality you can expect.",
  },
  {
    title: "What’s your refund policy?",
    content:
      "All credit purchases are final. If you experience a technical issue, reach out to support@imai.ai—we're here to help.",
  },
  {
    title: "Is IMAI planning to release new features?",
    content:
      "Yes, we're actively developing new features like style presets, user profiles, and advanced prompt tuning. Follow us on social media or join our newsletter for updates.",
  },
];

export default faqs;
